name: "Deploy Frontend to S3"
description: "Builds and deploys the React frontend to AWS S3"
inputs:
   slug:
     required: true
     description: "slug for deb file: Valkka-$VER-slug.deb, say, slug=Ubuntu20"

runs:
  using: "composite"
  steps:

  - name: Download external libraries
    shell: bash
    run: ./prepare_build.bash

  - name: Run easy_build.bash
    shell: bash
    run: ./easy_build.bash

  - name: Run make package
    shell: bash
    run: |
      cd build_dir
      make package
      cd ..

  - name: Save deb artifact
    shell: bash
    run: |
      cp build_dir/Valkka-${{ github.ref }}-Linux.deb ${{ github.workspace }}/Valkka-${{ github.ref }}-${{ inputs.slug }}.deb
      ls *.deb

  # https://github.com/actions/upload-artifact/issues/120
  - name: Publish deb artifact
    uses: actions/upload-artifact@v2
    with:
      name: Valkka-${{ github.ref }}-${{ inputs.slug }}.deb
      path: ${{ github.workspace }}/Valkka-${{ github.ref }}-${{ inputs.slug }}.deb

  # https://github.com/softprops/action-gh-release/blob/master/action.yml
  - name: Create a release
    uses: softprops/action-gh-release@v1
    with:
      files: Valkka-${{ github.ref }}-${{ inputs.slug }}.deb
