docker-create:
    runs-on: ubuntu-latest
    needs: [release]
    steps:

    - name: Update virtual machine
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y curl docker

    - name: Check version tag
      shell: bash
      # god'damn trial and error to find out the f-git tag !
      # https://docs.github.com/en/actions/learn-github-actions/variables
      run: |
        echo "VERSION2 = "$GITHUB_REF
        echo "VER=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        tail -n1 $GITHUB_ENV

    - name: Test environmental variables
      shell: bash
      run: |
        echo "VERSION TAG IS   : "$VER
        echo "VERSION FROM env.: "${{ env.VER }}

    - name: Fetch Dockerfile
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/elsampsa/valkka-core/master/Dockerfile -o Dockerfile
      working-directory: ${{ github.workspace }}

    - name: Fetch .deb package
      shell: bash
      run: |
        URL="https://github.com/elsampsa/valkka-core/releases/download/${{ env.VER }}/Valkka-${{ env.VER }}-Ubuntu22.deb"
        curl -L $URL -o Valkka.deb
      working-directory: ${{ github.workspace }}

    - name: Build Docker image
      shell: bash
      run: docker build -t valkka:${{ env.VER }} .
      working-directory: ${{ github.workspace }}

    - name: Log in to Docker Hub
      shell: bash
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      shell: bash
      run: |
        docker tag valkka:${{ env.VER }} ${{ secrets.DOCKERHUB_USERNAME }}/valkka:${{ env.VER }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/valkka:${{ env.VER }}
        docker tag valkka:${{ env.VER }} ${{ secrets.DOCKERHUB_USERNAME }}/valkka:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/valkka:latest
