name: Build and Package
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-Ubuntu20:
    runs-on: ubuntu-latest

    steps:

      - name: Update virtual machine
        run: | 
          sudo apt-get update -y 
          sudo apt-get install -y python3 mesa-utils glew-utils python3-numpy v4l-utils python3-pip openssl 
          sudo apt-get install -y build-essential yasm cmake pkg-config swig libglew-dev mesa-common-dev python3-dev python3-numpy libasound2-dev libssl-dev coreutils freeglut3-dev

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run easy_build.bash
        run: ./easy_build.bash

      - name: Run make package
        run: |
          cd build_dir
          make package
          cd ..

      - name: Save deb artifact
        run: |
          VER=$(echo "${{ github.ref }}" | sed -n 's/refs\/tags\///p')
          cp build_dir/Valkka-${VER}-Linux.deb ${{ github.workspace }}/Valkka-${VER}-Ubuntu20.deb

      - name: Publish deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: Valkka-${VER}-Ubuntu20.deb
          path: ${{ github.workspace }}/Valkka-${VER}-Ubuntu20.deb
